SELECT * FROM ACTOR;
SELECT * FROM FILM;
SELECT * FROM CUSTOMER;
SELECT TITLE FROM FILM;
SELECT DISTINCT LANGUAGE_ID AS LANGUAGE
FROM FILM;
SELECT COUNT(STORE_ID) FROM STORE;
SELECT LAST_NAME FROM STAFF;
SELECT COUNT(STAFF_ID) FROM STAFF;
SELECT FIRST_NAME FROM STAFF;
SELECT FIRST_NAME, LAST_NAME, COUNT(STAFF_ID), COUNT(STORE_ID) FROM STAFF;